---
- name: Respaldar objetos para la actualizacion de certificados
  hosts: 10.1.99.155
  become: yes 
  become_user: root

  tasks:
    - name: Detener servicio eap7-domain.service
      ansible.builtin.systemd:
        name: eap7-domain.service
        state: stopped
