---
- name: Copiar los objetos al destino para la actualizacion de certificados
  hosts: 10.1.99.155
  become: yes 
  become_user: root

  tasks:

  - name: copiar index.html
    ansible.builtin.copy:
      src: /home/ansible/habilitantes_ansible/certificados/10.1.99.155/fitappdesa.austro.grpfin.jks
      dest: /home/usrfit
      owner: root
      group: root
      mode: '0644'  
